postgres:
  hostname: "localhost"
  port: 5432
  db_name: "postgres"
  user: "postgres"
  password: "postgres"

redis:
  url: "redis://localhost:6379"

broadcasters: 
  - !BeaconClient
    url: "http://127.0.0.1:60869"

beacon_clients:
  - url: "http://127.0.0.1:60869"

network_config:
  !Custom
    dir_path: "./chain-info.yml"
    genesis_validator_root: "0xd61ea484febacfae5298d52a2b581f3e305a51f3112a9241b968dccf019f7b11"
    genesis_time: 1724321576


simulator: 
  url: "http://127.0.0.1:60830"

logging: "Console"