postgres:
  hostname: "localhost"
  port: 5432
  db_name: "postgres"
  user: "postgres"
  password: "postgres"

redis:
  url: "redis://localhost:6379"

broadcasters: 
  - !BeaconClient
    url: "http://127.0.0.1:51530"

beacon_clients:
  - url: "http://127.0.0.1:51530"

network_config:
  !Custom
    dir_path: "./chain-info.yml"
    genesis_validator_root: "0x68c9a86ac87db548086ed316fc4515355ff08e9b1e9a3361ab243584b933752f"
    genesis_time: 1724227003

simulator: 
  url: "http://127.0.0.1:51510"

logging: "Console"
