postgres:
  hostname: "localhost"
  port: 5432
  db_name: "postgres"
  user: "postgres"
  password: "postgres"

redis:
  url: "redis://localhost:6379"

broadcasters: 
  - !BeaconClient
    url: "http://127.0.0.1:33001"

beacon_clients:
  - url: "http://127.0.0.1:33001"

network_config: 
  !Custom
    dir_path: "./chain-info.yml"
    genesis_validator_root: "0xf46823260c2f95df6f0dcb3e0117f88784fde9a5f54c59612c881d82b2a57805"
    genesis_time: 1727185220

simulator: 
  url: "http://127.0.0.1:32002"

logging: "Console"
