volumes:
  psql_data:
    driver: local

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  db:
    build: .
    restart: always
    volumes:
      - './psql_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
